# Generated by Django 2.0 on 2018-12-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_auto_20181204_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'proxy': True,
                'indexes': [],
            },
            bases=('catalog.author',),
        ),
    ]
